### PR TITLE
Fixed the deprecated call introduced in atom v0.189

### PR DESCRIPTION
**Pull request by benjiro**
Fixed the deprecated call introduced in atom v0.189

```
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `seti-syntax` package
```

### CODE REVIEW

**Comment by ikeagold** [comment]
@benjiro thank you!

**Comment by CaptSaltyJack** [comment]
Cool! And...?? Can someone approve and merge this?

**Comment by stychu** [comment]
Ok guys some1 can help me how to apply this fix. ?

**Comment by asantos3** [comment]
The author of this theme, @jesseweed, needs to merge this pull request and launch another version with this fix. You shouldn't have to do nothing.

**Comment by call-a3** [comment]
:+1:

**Comment by Koxzi95** [comment]
Could be pulled really. Annoying to have the issue in atom :smile:

**Comment by jesseweed** [comment]
Sorry guys, been out of town. This should be fixed in v 0.4

**Comment by asantos3** [comment]
Close issue #67 and duplications of it?

**Pull request closed without merging**
